name: Jar Release

on:
  pull_request:
    branches: [ release ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 8 ]
        os: [ Ubuntu-20.04 ]
        maven: [ '3.6.3' ]
    runs-on: {{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: {{ matrix.java }}
          java-package: jdk
          maven-version: {{ matrix.maven }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6